export const VALIDATE_FORM = 'VALIDATE_FORM';
export const VALIDATE_FORM_SUCCESS = 'VALIDATE_FORM_SUCCESS';
export const VALIDATE_FORM_FAIL = 'VALIDATE_FORM_FAIL';

export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';

export const DOWNLOAD_BOOKS = 'DOWNLOAD_BOOKS';
export const DOWNLOAD_BOOKS_SUCCESS = 'DOWNLOAD_BOOKS_SUCCESS';
export const DOWNLOAD_BOOKS_FAIL = 'DOWNLOAD_BOOKS_FAIL';

export const GET_DELETE_BOOK = 'GET_DELETE_BOOK';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL'; 

export const GET_EDIT_BOOK = 'GET_EDIT_BOOK';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAIL = 'GET_BOOK_FAIL';

export const EDIT_BOOK = 'EDIT_BOOK';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAIL = 'EDIT_BOOK_FAIL'; 
